name: whatsapp-api

services:
  redis:
    image: docker.io/bitnami/redis:7.0
    hostname: redis
    env_file: ./.docker/.env.redis
    networks:
      - default
    volumes:
      - redis_data:/bitnami/redis

  api:
    image: devantage/devzappi
    build: .
    hostname: api
    env_file: ./.docker/.env.api
    networks:
      - default
    ports:
      - 3333:3333
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local

networks:
  default:
